
import 'package:flutter_application_10/core/models/song_model.dart';

final List<SongModel> globalSongsList = [
  SongModel(
    title: 'Alone', 
    artist: 'Alan Walker', 
    coverUrl: 'assets/images/alone_poster.jpg', 
    hasLyrics: true,
    audioURL: 'https://cs1.mp3.pm/download/70605445/QmFaRmwyNll4ZGtNelZyZFFNaUR6YUY3b2Z1aVlOYWZORVJ3a1R6VFByOUt4MUNLVk9nQ3YxZkNPenVWOEdCZ0I1TGNGeFIyVEV6WjJUbzYxZVlLYnhLYllHdFcvb3pDSm9kYWx1clFxYnpLZ3JnTDhxc2YwbjZzRlpMT2JtTmI/Coldplay_ft._Imagine_Dragons_-_Believe_(mp3.pm).mp3',
  ),
  SongModel(
    title: 'Let me love you', 
    artist: 'Justin Bieber feat DJ Snake', 
    coverUrl: 'assets/images/let_me_love_u.jpg', 
    hasLyrics: true,
    audioURL: 'https://cs1.mp3.pm/download/70605445/QmFaRmwyNll4ZGtNelZyZFFNaUR6YUY3b2Z1aVlOYWZORVJ3a1R6VFByOUt4MUNLVk9nQ3YxZkNPenVWOEdCZ0I1TGNGeFIyVEV6WjJUbzYxZVlLYnhLYllHdFcvb3pDSm9kYWx1clFxYnpLZ3JnTDhxc2YwbjZzRlpMT2JtTmI/Coldplay_ft._Imagine_Dragons_-_Believe_(mp3.pm).mp3',
  ),
  SongModel(
    title: 'Ignite', 
    artist: 'Alan Walker', 
    coverUrl: 'assets/images/ignite.jpg', 
    hasLyrics: true,
    audioURL: 'https://cs1.mp3.pm/download/70605445/QmFaRmwyNll4ZGtNelZyZFFNaUR6YUY3b2Z1aVlOYWZORVJ3a1R6VFByOUt4MUNLVk9nQ3YxZkNPenVWOEdCZ0I1TGNGeFIyVEV6WjJUbzYxZVlLYnhLYllHdFcvb3pDSm9kYWx1clFxYnpLZ3JnTDhxc2YwbjZzRlpMT2JtTmI/Coldplay_ft._Imagine_Dragons_-_Believe_(mp3.pm).mp3',
  ),
  SongModel(
    title: 'Taki Taki', 
    artist: 'DJ Snake feat Selena Gomez', 
    coverUrl: 'assets/images/taki_taki.jpg', 
    hasLyrics: true,
    audioURL: 'https://cs1.mp3.pm/download/70605445/QmFaRmwyNll4ZGtNelZyZFFNaUR6YUY3b2Z1aVlOYWZORVJ3a1R6VFByOUt4MUNLVk9nQ3YxZkNPenVWOEdCZ0I1TGNGeFIyVEV6WjJUbzYxZVlLYnhLYllHdFcvb3pDSm9kYWx1clFxYnpLZ3JnTDhxc2YwbjZzRlpMT2JtTmI/Coldplay_ft._Imagine_Dragons_-_Believe_(mp3.pm).mp3',
  ),
  SongModel(
    title: 'Believer', 
    artist: 'Imagine Dragons', 
    coverUrl: 'assets/images/believer.jpg', 
    hasLyrics: true,
    audioURL: 'https://cs1.mp3.pm/download/70605445/QmFaRmwyNll4ZGtNelZyZFFNaUR6YUY3b2Z1aVlOYWZORVJ3a1R6VFByOUt4MUNLVk9nQ3YxZkNPenVWOEdCZ0I1TGNGeFIyVEV6WjJUbzYxZVlLYnhLYllHdFcvb3pDSm9kYWx1clFxYnpLZ3JnTDhxc2YwbjZzRlpMT2JtTmI/Coldplay_ft._Imagine_Dragons_-_Believe_(mp3.pm).mp3',
  ),
  SongModel(
    title: 'Blinding Lights', 
    artist: 'The Weeknd', 
    coverUrl: 'assets/images/Blinding_Lights.png', 
    hasLyrics: true,
    audioURL: 'https://cs1.mp3.pm/download/70605445/QmFaRmwyNll4ZGtNelZyZFFNaUR6YEZ7b2Z1aVlOYWZORVJ3a1R6VFByOUt4MUNLVk9nQ3YxZkNPenVWOEdCZ0I1TGNGeFIyVEV6WjJUbzYxZVlLYnhLYllHdFcvb3pDSm9kYWx1clFxYnpLZ3JnTDhxc2YwbjZzRlpMT2JtTmI/Coldplay_ft._Imagine_Dragons_-_Believe_(mp3.pm).mp3',
  ),
  SongModel(
    title: 'Shape of You', 
    artist: 'Ed Sheeran', 
    coverUrl: 'assets/images/Shape_Of_You.jpg', 
    hasLyrics: false,
    audioURL: 'https://cs1.mp3.pm/download/70605445/QmFaRmwyNll4ZGtNelZyZFFNaUR6YUY3b2Z1aVlOYWZORVJ3a1R6VFByOUt4MUNLVk9nQ3YxZkNPenVWOEdCZ0I1TGNGeFIyVEV6WjJUbzYxZVlLYnhLYllHdFcvb3pDSm9kYWx1clFxYnpLZ3JnTDhxc2YwbjZzRlpMT2JtTmI/Coldplay_ft._Imagine_Dragons_-_Believe_(mp3.pm).mp3',
  ), 
  SongModel(
    title: 'Stay', 
    artist: 'The Kid LAROI & Justin Bieber', 
    coverUrl: 'assets/images/Stay.jpg', 
    hasLyrics: true,
    audioURL: 'https://cs1.mp3.pm/download/70605445/QmFaRmwyNll4ZGtNelZyZFFNaUR6YUY3b2Z1aVlOYWZORVJ3a1R6VFByOUt4MUNLVk9nQ3YxZkNPenVWOEdCZ0I1TGNGeFIyVEV6WjJUbzYxZVlLYnhLYllHdFcvb3pDSm9kYWx1clFxYnpLZ3JnTDhxc2YwbjZzRlpMT2JtTmI/Coldplay_ft._Imagine_Dragons_-_Believe_(mp3.pm).mp3',
  ),
  SongModel(
    title: 'Mockingbird', 
    artist: 'Eminem', 
    coverUrl: 'assets/images/mockingbird.jpg', 
    hasLyrics: true,
    audioURL: 'https://cs1.mp3.pm/download/70605445/QmFaRmwyNll4ZGtNelZyZFFNaUR6YUY3b2Z1aVlOYWZORVJ3a1R6VFByOUt4MUNLVk9nQ3YxZkNPenVWOEdCZ0I1TGNGeFIyVEV6WjJUbzYxZVlLYnhLYllHdFcvb3pDSm9kYWx1clFxYnpLZ3JnTDhxc2YwbjZzRlpMT2JtTmI/Coldplay_ft._Imagine_Dragons_-_Believe_(mp3.pm).mp3',
  ),
  SongModel(
    title: 'Another Love', 
    artist: 'Tom Odell', 
    coverUrl: 'assets/images/another_love.jpg', 
    hasLyrics: false,
    audioURL: 'https://cs1.mp3.pm/download/70605445/QmFaRmwyNll4ZGtNelZyZFFNaUR6YUY3b2Z1aVlOYWZORVJ3a1R6VFByOUt4MUNLVk9nQ3YxZkNPenVWOEdCZ0I1TGNGeFIyVEV6WjJUbzYxZVlLYnhLYllHdFcvb3pDSm9kYWx1clFxYnpLZ3JnTDhxc2YwbjZzRlpMT2JtTmI/Coldplay_ft._Imagine_Dragons_-_Believe_(mp3.pm).mp3',
  ), 
  SongModel(
    title: 'Night Changes', 
    artist: 'One Direction', 
    coverUrl: 'assets/images/night_changes.jpg', 
    hasLyrics: true,
    audioURL: 'https://cs1.mp3.pm/download/70605445/QmFaRmwyNll4ZGtNelZyZFFNaUR6YUY3b2Z1aVlOYWZORVJ3a1R6VFByOUt4MUNLVk9nQ3YxZkNPenVWOEdCZ0I1TGNGeFIyVEV6WjJUbzYxZVlLYnhLYllHdFcvb3pDSm9kYWx1clFxYnpLZ3JnTDhxc2YwbjZzRlpMT2JtTmI/Coldplay_ft._Imagine_Dragons_-_Believe_(mp3.pm).mp3',
  ),
  SongModel(
    title: 'Cheap Thrills', 
    artist: 'Sia', 
    coverUrl: 'assets/images/cheap.jpg', 
    hasLyrics: true,
    audioURL: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3', 
  ),
  SongModel(
    title: 'Harley’s in Hawaii', 
    artist: 'Katy Perry', 
    coverUrl: 'assets/images/harleys.jpg', 
    hasLyrics: true,
    audioURL: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3', 
  ),
 SongModel(
    title: 'Daily Mix 1', 
    artist: 'Spotify', 
    coverUrl: 'assets/images/imagine_dragons.jpg',
    hasLyrics: false,
    audioURL: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
  ),
  SongModel(
    title: 'Discover Weekly', 
    artist: 'Spotify', 
    coverUrl: 'assets/images/alone_poster.jpg', 
    hasLyrics: false,
    audioURL: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
  ),
];